config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get 'searches/search' => 'searches#search'
  get 'homes/about' => 'homes#about'
  delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
  get 'customers/resign' => 'customers#resign'
  patch 'customers/resign' => 'customers#resign_update'
  get 'orders/thanks' => 'orders#thanks'

  resource :customers,except: :create do
  resources :addresses
   end
  resources :products, only: [:index,:show]
  resources :genres, only: [:index] do
  end
  resources :order_products
  resources :cart_products, only:[:create, :index, :update, :destroy]
  resources :orders do
    collection do
      post :confirm
    end
  end

  devise_for :customers ,controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :admins  ,controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    get 'orders/number' => 'orders#number'
    resources :orders, only:[:index, :show, :update]
    resources :customers
    resources :products, only: [:index,:new,:create,:show,:edit,:update]
    resources :order_products, only: [:update]
    resources :genres, only: [:index,:edit,:create,:update]
  end
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :quantity, numericality: :only_integer

  def subtotal
    (quantity * product.price * 1.1).floor
  end

  def self.cart_products_total_price(cart_products)
    array = []
    cart_products.each do |cart_product|
      array << cart_product.product.price * cart_product.quantity
    end
    return (array.sum * 1.1).floor
  end

end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.customer_id = current_customer.id
    if current_customer.cart_products.find_by(product_id: params[:cart_product][:product_id]).present?
      cart_product = current_customer.cart_products.find_by(product_id: params[:cart_product][:product_id])
      cart_product.quantity += params[:cart_product][:quantity].to_i
      cart_product.save
      flash[:notice] = "商品をカートに入れました"
      redirect_to cart_products_path
    elsif @cart_product.save
      flash[:notice] = "商品をカートに入れました"
      redirect_to cart_products_path
    end
  end

  def index
    @cart_products = current_customer.cart_products
    @cart_product = CartProduct.new
    @total_price = current_customer.cart_products.cart_products_total_price(@cart_products)
  end

  def update
    id = params[:cart_product][:id]
    @cart_product = CartProduct.find(params[:id])
    if params[:cart_product][:quantity] == "0"
      @cart_product.destroy
      flash[:notice] = "商品を削除しました"
      redirect_to cart_products_path
    elsif @cart_product.update(quantity: params[:cart_product][:quantity])
      flash[:notice] = "商品数を変更しました"
      redirect_to cart_products_path
    else
      @cart_products = current_customer.cart_products
      @total_price = current_customer.cart_products.cart_products_total_price(@cart_products)
      render "cart_products/index"
    end
  end

  def destroy
    current_customer.cart_products.find(params[:id]).destroy
    flash[:notice] = "商品を削除しました"
    redirect_to cart_products_path
  end

  def destroy_all
    current_customer.cart_products.destroy_all
    flash[:notice] = "カート内全商品を削除しました"
    redirect_to cart_products_path
  end

  private
  def cart_product_params
    params.require(:cart_product).permit(:product_id, :quantity)
  end

end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/index.html.erb
<h1>ショッピングカート</h1>
<div class="row">
  <div class="col-xs-4 col-xs-offset-1">
  </div>
  <div class="col-xs-1 col-xs-offset-8">
    <%= link_to cart_products_destroy_all_path, method: :delete do %>
      <button class="btn btn-danger">カートを空にする</button>
    <% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-xs-10">
    <%= render "layouts/error_message", model: @cart_product  %>
    <table class="table">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税抜）</th>
          <th>数量</th>
          <th>小計</th>
          <th>　</th>
        </tr>
      </thead>
      <% @cart_products.each do |cart_product| %>
        <tr>
          <td>
            <%= attachment_image_tag cart_product.product, :image, :fill, 50, 50, format:'jpeg', fallback:"no_image.jpg", size:"50x50" %>
            <%= cart_product.product.name %>
          </td>
          <td>
            <%= (cart_product.product.price ) %>
          </td>
          <td>
            <%= form_with model: cart_product, url: cart_product_path(cart_product), local: true do |f| %>
              <%= f.hidden_field :id, :value => cart_product.id %>
              <%= f.text_field :quantity, :size => "5" %>　<%= f.submit "変更" %>
            <% end %>
          </td>
          <td><%= cart_product.subtotal %></td>
          <td>
            <%= link_to cart_product_path(cart_product), method: :delete do %>
              <button>削除</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-xs-1">
    <%= link_to root_path do %>
      <button class="btn btn-primary">買い物を続ける</button>
    <% end %>
  </div>
  <div class="col-xs-3 col-xs-offset-9">
    <table class="table table-bordered">
      <tr>
        <th>合計金額</th>
        <td><%= @total_price %></td>
      </tr>
    </table>
  </div>
</div>
<div class="row">
  <% if current_customer.cart_products.any? %>
    <div class="col-xs-4 col-xs-offset-4">
      <% if current_customer.cart_products.any? %>
        <%= link_to new_order_path do %>
          <button class="btn btn-success">情報入力に進む</button>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>