config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get 'searches/search' => 'searches#search'
  get 'homes/about' => 'homes#about'
  delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
  get 'customers/resign' => 'customers#resign'
  patch 'customers/resign' => 'customers#resign_update'
  get 'orders/thanks' => 'orders#thanks'

  resource :customers,except: :create do
  resources :addresses
   end
  resources :products, only: [:index,:show]
  resources :genres, only: [:index] do
  end
  resources :order_products
  resources :cart_products, only:[:create, :index, :update, :destroy]
  resources :orders do
    collection do
      post :confirm
    end
  end

  devise_for :customers ,controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :admins  ,controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    get 'orders/number' => 'orders#number'
    resources :orders, only:[:index, :show, :update]
    resources :customers
    resources :products, only: [:index,:new,:create,:show,:edit,:update]
    resources :order_products, only: [:update]
    resources :genres, only: [:index,:edit,:create,:update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :in_cart_products, through: :cart_products, source: :product
  has_many :orders, dependent: :destroy
  has_many :order_products, through: :orders
  has_many :purchased_products, through: :order_products, source: :product
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :postalcode, format: {with: /\A[0-9]{7}\z/}
  validates :family_name_kana, presence: true, format: {
                  with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/
                }
  validates :first_name_kana, presence: true, format: {
                  with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/
                }


end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
    before_action :authenticate_admin!

    def index
        @customers = Customer.all
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    def update
        @customer = Customer.find(params[:id])
        if @customer.update(customer_params)
            flash[:notice] = "お客様情報を更新しました"
            redirect_to admins_customers_path
        else
            render 'admins/customers/edit'
        end
    end

    def show
        @customer = Customer.find(params[:id])
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    private

    def customer_params
        params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postalcode, :address, :tel, :email, :is_deleted)
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]
  

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。新規登録から行ってください。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
  end

  def edit
  end

  def update
    if current_customer.update(customer_params)
      flash[:notice] = "お客様情報を更新しました"
      redirect_to customers_path(current_customer)
    else
      render "edit"
    end
  end

  def resign
  end

  def resign_update
    current_customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ご利用ありがとうございました"
    redirect_to root_path
  end

  private
  def customer_params
  params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postalcode, :address, :email,:tel)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h1>登録情報編集</h1>
<%= form_with(model: current_customer, url:customers_path(current_customer),local:true) do |f|%>
  <%= render 'layouts/error_message', model: f.object %>
  <table class = "table">
    <tr>
      <th>名前</th>
      <td><%= f.text_field :family_name, class: "form-control" %></td>
      <td><%= f.text_field :first_name, class: "form-control" %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= f.text_field :family_name_kana, class: "form-control" %></td>
      <td><%= f.text_field :first_name_kana, class: "form-control" %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= f.email_field :email, class: "form-control"%></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>郵便番号（ハイフンなし）</th>
      <td><%= f.text_field :postalcode, class: "form-control" %></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>住所</th>

      <td><%= f.text_field :address, class: "form-control"%></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th>電話番号（ハイフンなし）</th>
      <td><%= f.text_field :tel, class: "form-control" %></td>
      <td>&nbsp;</td>
    </tr>
  </table>
  <%= f.submit '編集内容を保存する' ,class:"btn btn-primary"%>　<%=link_to '退会する', customers_resign_path,class:"btn btn-danger"%>
<% end %>

app/views/customers/resign.html.erb
<p>本当に退会しますか？</p>
<p>退会すると、会員登録情報や<br>
これまでの購入履歴が閲覧できなくなります。<br>
退会する場合は、「退会する」をクリックしてください。</p>
<%= link_to'退会しない', :back, class:"btn btn-primary"%>
<%= link_to '退会する', customers_resign_path ,method: :patch, "data-confirm" => "本当に退会しますか？", class:"btn btn-danger"%>

app/views/customers/show.html.erb
<h1>マイページ</h1>
<br>
<table class = "table">
  <tbody>
    <tr>
      <th class="table-heading">氏名</th>
      <td><%=current_customer.family_name%>　<%=current_customer.first_name%></td>
    </tr>
    <tr>
      <th class="table-heading">カナ</th>
      <td><%=current_customer.family_name_kana%>　<%=current_customer.first_name_kana%></td>
    </tr>
    <tr>
      <th class="table-heading">郵便番号</th>
      <td><%=current_customer.postalcode%></td>
    </tr>
      <tr>
      <th class="table-heading">住所</th>
      <td><%=current_customer.address%></td>
    </tr>
      <tr>
      <th class="table-heading">電話番号</th>
      <td><%=current_customer.tel%></td>
    </tr>
      <tr>
      <th class="table-heading">メールアドレス</th>
      <td><%=current_customer.email%></td>
    </tr>
    <tr>
      <th>&nbsp;</th>
        <td>
          <%= link_to "編集する", edit_customers_path(current_customer) %>
        　<%= link_to "パスワードを変更する", edit_customer_password_path %>
        </td>
    </tr>
  </tbody>
</table>

<%= link_to"配送先一覧",customers_addresses_path,class:"btn btn-primary"%>
<%= link_to"注文履歴一覧",orders_path,class:"btn btn-primary"%>