config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get 'searches/search' => 'searches#search'
  get 'homes/about' => 'homes#about'
  delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
  get 'customers/resign' => 'customers#resign'
  patch 'customers/resign' => 'customers#resign_update'
  get 'orders/thanks' => 'orders#thanks'

  resource :customers,except: :create do
  resources :addresses
   end
  resources :products, only: [:index,:show]
  resources :genres, only: [:index] do
  end
  resources :order_products
  resources :cart_products, only:[:create, :index, :update, :destroy]
  resources :orders do
    collection do
      post :confirm
    end
  end

  devise_for :customers ,controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :admins  ,controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    get 'orders/number' => 'orders#number'
    resources :orders, only:[:index, :show, :update]
    resources :customers
    resources :products, only: [:index,:new,:create,:show,:edit,:update]
    resources :order_products, only: [:update]
    resources :genres, only: [:index,:edit,:create,:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postalcode ,presence: :true
  validates :postalcode, format: {with: /\A[0-9]{7}\z/}
  validates :address ,presence: :true
  validates :delivery_name ,presence: :true

   def order_addresses
    ( self.postalcode + ' ' + self.address + ' ' + self.delivery_name )
   end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :quantity, numericality: :only_integer

  def subtotal
    (quantity * product.price * 1.1).floor
  end

  def self.cart_products_total_price(cart_products)
    array = []
    cart_products.each do |cart_product|
      array << cart_product.product.price * cart_product.quantity
    end
    return (array.sum * 1.1).floor
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_products, dependent: :destroy
  has_many :in_cart_products, through: :cart_products, source: :product
  has_many :orders, dependent: :destroy
  has_many :order_products, through: :orders
  has_many :purchased_products, through: :order_products, source: :product
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :postalcode, format: {with: /\A[0-9]{7}\z/}
  validates :family_name_kana, presence: true, format: {
                  with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/
                }
  validates :first_name_kana, presence: true, format: {
                  with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/
                }


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name ,presence: true
  validates :is_active, inclusion: [true, false]
  # validates :is_active, presence: true　falseが入るとfalseが入ったときに弾かれてしまうので上の記述に変更
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  belongs_to :customer

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status:  {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  validates :postalcode, presence: true
  validates :delivery_name, presence: true
  validates :delivery_address, presence: true

   def address_already_registerd?(current_customer)
     current_customer.address != delivery_address && current_customer.addresses.where(address: delivery_address).empty?
   end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  enum product_status: {着手不可:0, 制作待ち:1, 製作中:2, 制作完了:3}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def tax_price
    (self.price * 1.1).floor
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @genres = Genre.where(is_active: true)
    if params[:genre_id]
  		@genre = Genre.find(params[:genre_id])
  		@products = @genre.products.order(created_at: :desc).where(is_active: true).page(params[:page])
    else
      @products = Product.where(is_active: true).page(params[:page])
    end

    @product_first = Product.find_by(id: 1)
    @product_second = Product.find_by(id: 2)
    @product_third = Product.find_by(id: 3)
    @product_fourth = Product.find_by(id: 4)

  end

  def about
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error-explanation" class="alert alert-danger">
    <h2><%= model.errors.count %>件のエラーが発生しました</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="header">
        <div class="logo"><div class="shop-image"></div></div>
          <% if admin_signed_in? %>
            <div class="admin-searchbar">
              <%= form_with url: searches_search_path, method: :get, local: true do |f| %>
                <%= f.select :range, options_for_select([['---選択してください---', ''],['Customer', '1'],['Product', '2']]) %>
                <%= f.text_field :word %>
                <%= f.submit "検索" %>
              <% end %>
            </div>
          <% end %>
          <div class="header-list">
            <nav>
              <ul>
                <% if customer_signed_in? %>
                  <li class="header-list-item"><%= link_to "トップ", root_path, class: "btn-primary" %></button></li>
                  <li class="header-list-item"><%= link_to "マイページ", customers_path(current_customer), class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "商品一覧", products_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "カート", cart_products_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn-primary" %></li>
                <% elsif admin_signed_in? %>
                  <li class="header-list-item"><%= link_to "商品一覧", admins_products_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "会員一覧", admins_customers_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "注文履歴一覧", admins_orders_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "ジャンル一覧", admins_genres_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn-primary" %></li>
                <% else %>
                  <li class="header-list-item"><%= link_to "トップ", root_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "About", homes_about_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "商品一覧", products_path, class: "btn-primary" %></li></a>
                  <li class="header-list-item"><%= link_to "新規登録", new_customer_registration_path, class: "btn-primary" %></li>
                  <li class="header-list-item"><%= link_to "ログイン", new_customer_session_path, class: "btn-primary"  %></li>
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer>
      <div class=footer-text>©️inc.Shabuyou.NaganoCake</div>
    </footer>
  </body>
</html>