config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get 'searches/search' => 'searches#search'
  get 'homes/about' => 'homes#about'
  delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
  get 'customers/resign' => 'customers#resign'
  patch 'customers/resign' => 'customers#resign_update'
  get 'orders/thanks' => 'orders#thanks'

  resource :customers,except: :create do
  resources :addresses
   end
  resources :products, only: [:index,:show]
  resources :genres, only: [:index] do
  end
  resources :order_products
  resources :cart_products, only:[:create, :index, :update, :destroy]
  resources :orders do
    collection do
      post :confirm
    end
  end

  devise_for :customers ,controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :admins  ,controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    get 'orders/number' => 'orders#number'
    resources :orders, only:[:index, :show, :update]
    resources :customers
    resources :products, only: [:index,:new,:create,:show,:edit,:update]
    resources :order_products, only: [:update]
    resources :genres, only: [:index,:edit,:create,:update]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_products, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def tax_price
    (self.price * 1.1).floor
  end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "商品を登録しました"
      redirect_to admins_product_path(@product)
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "商品情報を更新しました"
      redirect_to admins_product_path(params[:id])
    else
      render 'edit'
    end
  end

private
  def product_params
    params.require(:product).permit(:image,:name,:price,:introduction,:is_active,:genre_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @genres = Genre.where(is_active: true)
    if params[:genre_id]
		  @genre = Genre.find(params[:genre_id])
		  @products = @genre.products.order(created_at: :desc).where(is_active: true).page(params[:page])
    else
      @products = Product.where(is_active: true).page(params[:page])
    end
 end

 def show
   @product = Product.find(params[:id])
   @genres = Genre.where(is_active: true)
   @cart_product = CartProduct.new
 end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_genrebox.html.erb
<table class="table">
	<thead>
		<tr>
		<th>ジャンル検索</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= link_to "すべての商品", products_path %></td>
		</tr>
		<% genres.each do |genre| %>
			<tr>
				<td><%= link_to genre.name, products_path(genre_id: genre.id) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/products/index.html.erb
<h1>
<% if params[:genre_id] %>
  <%= @genre.name %>
<% else %>
  すべての商品
<% end %>
</h1>
<div class="row">
  <div class="col-md-3">
    <div class="genre-box">
      <%= render 'genrebox', genres: @genres %>
    </div>
  </div>
  <div class="genres-container">
    <div class="col-md-9" >
      <strong> 全<%= @products.length %>件 </strong>
      <div class="genre-list">
        <br>
        <% @products.each do |product| %>
          <% if product.genre.is_active == true %>
            <div class="genre-list-item">
              <%= link_to product_path(product) do %>
                <%= attachment_image_tag product, :image, :limit, 100,100, format: 'jpeg', fallback: 'no_image.jpg',size: "200x200" %>
              <% end %>
              <br>
              <%= product.name %>
              <%= (product.price * 1.1).floor%>円(税込)
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= paginate @products %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= render 'genrebox', genres: @genres %>
  </div>
  <div class="col-xs-9">
    <div class="row">
      <div class="col-xs-5">
        <div class="product-imag">
          <table class="table">
            <tr>
              <th><%= attachment_image_tag @product, :image, :limit, 300, 300, fallback: "no_image.jpg",size: "320x320" %></th>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-xs-7">
        <table class="table">
          <tr>
            <th>
              <%= @product.name %>
            </th>
          </tr>
          <tr>
            <td>
              <%= @product.introduction %>
            </td>
          </tr>
          <tr>
            <td>¥<%= (@product.price * 1.1).floor %>円(税込)</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="text-right">
        <%= form_with model: @cart_product, url: cart_products_path, local: true do |f| %>
          <%= f.select :quantity, Array.new(10){|index| ["#{index+ 1}個",index+1] } %>
          <%= f.hidden_field :product_id, :value => @product.id %>
          <%= f.submit 'カートにいれる', class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>